### ISSUE TITLE
.NET CORE?

### ISSUE THREAD

**Issue by rockxl1** [arnoldasgudas/Hangfire.MySqlStorage#12]
When you will release the .NET CORE Version?
I am so looking forward to the release 👍

**Comment by dsoronda** [comment]
+1

**Comment by aford22** [comment]
+1

**Comment by paurail** [comment]
+1

**Comment by LordMike** [comment]
Hi there. At my work we've made a version of this that's been converted to .NET Core (project json format), which we'll now begin testing. To do so, we've:

* Used `SapientGuardian.Mysql.Data`
* Changed the use of transactions to directly use MySQL's transactions
* Removed support for the ConfigurationManager system
* Ignored the tests

If @arnoldasgudas wishes, I can upload a version that shows this, but it currently doesn't support .NET. So extra work has to be put in to support both targets simultaneously.

**Comment by arnoldasgudas** [comment]
Hi @LordMike,
I've created a [dotnetcore](https://github.com/arnoldasgudas/Hangfire.MySqlStorage/tree/dotnetcore) branch. Please push your version to this branch. Let's see if we can get help from the community to add .NET support and tests.

**Comment by LordMike** [comment]
Well. To be fair, I can't push to a branch in your repo.
I'll fork the project, create my changes (as little as possible), and do a PR.

**Comment by LordMike** [comment]
I have created a PR which:
* Migrates csproj' files to VS2017 format
* Targets `net45` and `netstandard1.6`
  * Uses `Mysql.Data` for `net45`
  * Uses `SapientGuardian.MySql.Data` for `netstandard1.6`

#21

**Comment by nvivo** [comment]
.Net Core version should reference [MySqlConnector](https://github.com/mysql-net/MySqlConnector) package instead of MySql.Data. It supports real async and for .net core is what people are using.

**Comment by nvivo** [comment]
Just in case anyone wants it, I ported the code to MySqlConnector, upgraded the package format and fixed some tests.

Repo: https://github.com/nvivo/Hangfire.MySqlStorage/
Package is available here: https://www.nuget.org/packages/Hangfire.MySqlStorage.MySqlConnector

**Comment by CruelMoney** [comment]
@nvivo just installed your package and everything seems to work, but I get the following error: 
``` 
Error occurred during execution of 'Worker #3f227eae' process. Execution will be retried (attempt #5) in 00:00:16 seconds.
System.TypeInitializationException: The type initializer for 'Hangfire.MySql.MySqlDistributedLock' threw an exception. ---> System.MissingMethodException: Method not found: 'Hangfire.Logging.ILog Hangfire.Logging.LogProvider.GetCurrentClassLogger()'.
```
Using core 2.0 and hangfire 1.6.17.

**Comment by vdurante** [comment]
I have tried this one and apparently it works

https://github.com/stulzq/Hangfire.MySql.Core

**Comment by mpwaldhorst** [comment]
Created a pull request which should fix some issues with newer versions of NuGet packages. Should also fix an infinite loop which would keep printing debug messages, more info [here](https://github.com/arnoldasgudas/Hangfire.MySqlStorage/pull/36).

**Comment by arnoldasgudas** [comment]
https://www.nuget.org/packages/Hangfire.MySqlStorage/2.0.0
