### ISSUE TITLE
HttpConfiguration does not contain a definition for 'UseStorage'

### ISSUE THREAD

**Issue by sajithk** [arnoldasgudas/Hangfire.MySqlStorage#16]
I'm trying to use MySqlStorage in Web API app. I installed NuGet package "Hangfire.MySqlStorage" version 1.0.3. When I configure Hangfire I''m getting following error,

HttpConfiguration does not contain a definition for 'UseStorage' and no extension method 'UseStorage' accepting a first argument of type 'HttpConfiguration' could be found (are you missing a using directive or an assembly reference?)

Seems I'm missing a reference here. Could not figure out.

**Comment by gblosser** [comment]
You don't use HttpConfiguration in this case.  You use GlobalConfiguration.

Example:
GlobalConfiguration.Configuration.UseStorage(
    new MySqlStorage(ConfigurationManager.ConnectionStrings["your_connection_string_here"].ConnectionString));

And continue with OWIN configuration:
app.UseHangfireDashboard();
app.UseHangfireServer();

**Comment by sajithk** [comment]
Thanks, @gblosser. You are correct. Actually, GlobalConfiguration should be Hangfire.GlobalConfiguration from the Hangfire.Core library.
