### ISSUE TITLE
Parameter '@rownum' must be defined

### ISSUE THREAD

**Issue by JackilMatto** [arnoldasgudas/Hangfire.MySqlStorage#2]
Hi...i got this exception in almost any page? any suggestion?

MySql.Data.MySqlClient.MySqlException: Parameter '@rownum' must be defined.

**Comment by arnoldasgudas** [comment]
Hi Jackil,
Try adding ```Allow User Variables=True``` in the connection string.

**Comment by JackilMatto** [comment]
it works ! Thank you..

**Comment by PaulatElf** [comment]
I have this issue too but only on my live website, when running from Visual Studio (localhost) don't have any problems but when using Hangfire (1.8.0) Dashboard on the live published site I can access a few pages (/hangfire, /hangfire/servers, /hangfire/jobs) but for all the other pages (such as hangfire/recurring, hangfire/retries, hangfire/jobs/succeeded  ect.) I always get that same message:  'MySqlException: Parameter '@rownum' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.'

Even though I already do have 'Allow User Variables=true' in the connection string.

If anyone has any ideas how to fix this it would be very helpful.

**Comment by sunnamed434** [comment]
> I have this issue too but only on my live website, when running from Visual Studio (localhost) don't have any problems but when using Hangfire (1.8.0) Dashboard on the live published site I can access a few pages (/hangfire, /hangfire/servers, /hangfire/jobs) but for all the other pages (such as hangfire/recurring, hangfire/retries, hangfire/jobs/succeeded ect.) I always get that same message: 'MySqlException: Parameter '@rownum' must be defined. To use this as a variable, set 'Allow User Variables=true' in the connection string.'
> 
> Even though I already do have 'Allow User Variables=true' in the connection string.
> 
> If anyone has any ideas how to fix this it would be very helpful.

Make sure to have every new word with a capital letter, not in lower case, ONLY like this: `Allow User Variables=True`.

For example, I had like `Allow User Variables=true` and `allow user variables=true` and both didn't work.
