### ISSUE TITLE
Nuget Release (1.0.3) not Working

### ISSUE THREAD

**Issue by hillin** [arnoldasgudas/Hangfire.MySqlStorage#25]
Hi,

The latest package on Nuget is not working, an ASP.NET Core app throws an exception on start up, which complains "MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" is not found. Turns out when installing this package from Nuget, a MySql.Data of version 6.9.9.0 is installed, instead of 6.9.8.0.

**Comment by hillin** [comment]
Workaround: run 
```Powershell
Install-Package MySql.Data -version 6.9.8
```
in the package manager console.

**Comment by arnoldasgudas** [comment]
Fixed with release 1.0.5
