### ISSUE TITLE
MySqlStorageConnection.AnnounceServer @id parameter definition problem

### ISSUE THREAD

**Issue by osoykan** [arnoldasgudas/Hangfire.MySqlStorage#3]
When i debug the announceserver method, i faced parameters are wrong and all values are going to database as null. 
Because` VALUE (@Id, @Data, @Heartbeat)` not same `new
                    {
                        id = serverId,
                        data = JobHelper.ToJson(new ServerData
                        {
                            WorkerCount = context.WorkerCount,
                            Queues = context.Queues,
                            StartedAt = DateTime.UtcNow,
                        }),
                        heartbeat = DateTime.UtcNow
                    }`

you see: nameof(id) != @Id, dapper is blowing in there.

So, I changed only parameter names. @Id to @id...

**Comment by arnoldasgudas** [comment]
Thanks for the update. 
I think ```"ON DUPLICATE KEY UPDATE Data = @Data, LastHeartbeat = @Heartbeat",``` should be updated as well the same way.

**Comment by osoykan** [comment]
yes exactly.

**Comment by osoykan** [comment]
committed.

**Comment by osoykan** [comment]
Thank you  for merge. It was critical error for me, im using release dll for now, you should publish new nuget package imho.

**Comment by arnoldasgudas** [comment]
Thanks. Package released: https://www.nuget.org/packages/Hangfire.MySqlStorage/1.0.1

**Comment by osoykan** [comment]
Thanks for package. I think, there is something wrong on new nuget package. Dll was same old one. Could you please check again ? or am I wrong.

**Comment by arnoldasgudas** [comment]
Uploaded new package: https://www.nuget.org/packages/Hangfire.MySqlStorage/1.0.2
Please check if it solved the issue

**Comment by osoykan** [comment]
Hi,

Thank you very much, it is solved.
