### ISSUE TITLE
Add a prefix to Tables - feature for 1.0.6 version

### ISSUE THREAD

**Issue by Iulian94** [arnoldasgudas/Hangfire.MySqlStorage#46]
Copy of https://github.com/arnoldasgudas/Hangfire.MySqlStorage/issues/7 

Can this be resolved also for the 1.0.6 version?
Most of the old projects have only been migrated to .Net 4.6, not Standard, but still need this for a separation from the business tables.

**Comment by arnoldasgudas** [comment]
Resolved in https://www.nuget.org/packages/Hangfire.MySqlStorage/2.0.0
