### ISSUE TITLE
MySqlStorage uses up all the connections in the pool

### ISSUE THREAD

**Issue by JackilMatto** [arnoldasgudas/Hangfire.MySqlStorage#5]
Over 50 connection created at startup ...some way or configuration to solve it?

**Comment by arnoldasgudas** [comment]
Opened connection count depends on Hangfire worker count. You can limit worker count by setting ```WorkerCount``` property value in ```BackgroundJobServerOptions```:
```
app.UseHangfireServer(
   new BackgroundJobServerOptions
   {
      WorkerCount = 1
   });
```

More info: http://hangfire.io/features.html#concurrency-level-control

**Comment by JackilMatto** [comment]
Thank you!
