### ISSUE TITLE
lowercase table names in mysql linux

### ISSUE THREAD

**Issue by cesarbmx** [arnoldasgudas/Hangfire.MySqlStorage#66]
I am running Hangfire on MySQL on Linux, which is case sensitive.

I am getting `Table Hangfire_DistributedLock doesn't exist`
![image](https://user-images.githubusercontent.com/1844530/75275645-3e209b00-57db-11ea-9b7b-64aaf3a867c1.png)

Is there any way to make Hangfire use lower case table names?

**Comment by tluyben** [comment]
You can put 

lower_case_table_names = 1

in your mysqld config, that works.
