### ISSUE TITLE
Use MySql.Data as dependency instead of MySqlConnector

### ISSUE THREAD

**Issue by azhe403** [arnoldasgudas/Hangfire.MySqlStorage#69]
I want to use MySql.Data but was available from MySqlConnector
Cause ambigous reference
![gambar](https://user-images.githubusercontent.com/17938038/76680251-96e49600-6619-11ea-9ba3-d5b7733b9b50.png)

this is dependecies
![gambar](https://user-images.githubusercontent.com/17938038/76696085-f5615100-66b9-11ea-8328-cee2eb4b0177.png)

**Comment by gao-artur** [comment]
If it will be done users of [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) that built on top of `MySqlConnector` will have the same issue as you.

**Comment by samcov** [comment]
Well, is it possible to get a version that doesn't depend on MySqlConnector.

I'm getting this issue in .net core.

**Comment by Faisal0sal** [comment]
I think I have the same issue. As soon as I add Hangfire.MySqlStorage;  Pomelo.EntityFrameworkCore.MySql will stop working. 

Issue says:

Could not load type 'MySql.Data.MySqlClient

**Comment by gao-artur** [comment]
You can resolve this with assembly alias
https://stackoverflow.com/a/57452070/2557855
