### ISSUE TITLE
Should be possible to add a prefix to Tables

### ISSUE THREAD

**Issue by ciccio86** [arnoldasgudas/Hangfire.MySqlStorage#7]
It should be possible to specify an option to add a prefix to the tables created by Hangfire so that there should not be conflicts in names if using existing database.

**Comment by void616** [comment]
I'm in. It would be good option.

**Comment by crazybird** [comment]
It would be good option.

**Comment by DaveOMac** [comment]
+1 please

**Comment by arnoldasgudas** [comment]
Added in https://www.nuget.org/packages/Hangfire.MySqlStorage/1.1.0-beta

**Comment by jchampeau** [comment]
I received the following error when trying to update from 1.05 to 1.1.0-beta:

Could not install package 'Hangfire.MySqlStorage 1.1.0-beta'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The hangfire.mysqlstorage.1.1.0-beta.nupkg contains lib/netstandard2.0/Hangfire.MySQL.dll  where as the previous releases 1.0.5 contained a net45 version of the dll.  Would it be possible to create a package with net45 support?

**Comment by Iulian94** [comment]
Can this be resolved also for the 1.0.6 version? 
Most of the old projects have only been migrated to .Net 4.6, not Standard, but still need this for a separation from the business tables.

**Comment by arnoldasgudas** [comment]
Resolved in https://www.nuget.org/packages/Hangfire.MySqlStorage/2.0.0
