### ISSUE TITLE
Dashboard met exceptions: "Parameter '@rank' must be defined."

### ISSUE THREAD

**Issue by percyboy** [arnoldasgudas/Hangfire.MySqlStorage#9]
Steps:
1. Open the dashboard
2. Click the "Jobs" at top left corner.
3. Exception occurs.

I checked the source code. The SQL is:

> public IEnumerable<int> GetEnqueuedJobIds(string queue, int @from, int perPage)
>         {
>             string sqlQuery = @"
> SET @rank=0;
> select r.JobId from (
>   select jq.JobId, @rank := @rank+1 AS rank 
>   from JobQueue jq
>   where jq.Queue = @queue
>   order by jq.Id
> ) as r
> where r.rank between @start and @end;";
> 
> ```
>         return _storage.UseConnection(connection =>
>             connection.Query<int>(
>                 sqlQuery,
>                 new {queue = queue, start = @from + 1, end = @from + perPage}));
>     }
> ```

It seems like `SET @rank=0;` is not working.

I'm using packages all from nuget and MySQL version 5.7(on ubuntu server).

**Comment by arnoldasgudas** [comment]
Hi percyboy,
There must be `Allow User Variables` parameter set to `True` in the connection string. For example: `server=127.0.0.1;uid=root;pwd=root;database={0};Allow User Variables=True`

Hope this helps

**Comment by LordMike** [comment]
Suggestion: Check if the option is set in the connection string, and throw an exception if it isn't.
Allow clients to indicate they explicitly want to allow this, by setting some flag in the configuration.. 

I believe most users will use a lot of time debugging this, where a helpful exception could lead them to a wiki/this issue.

**Comment by arnoldasgudas** [comment]
Fixed with release 1.0.5
